package com.chatRobot.model;

import java.util.Date;

public class custom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.C_NO
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private Integer cNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.C_NAME
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.ID_CARD
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.SEX
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.PHONE
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.ADDRESS
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.EMAIL
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.HOBBY
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column custom.CREATED_DATE
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    private Date createdDate;


    private String sdate;

    public String getSdate(){
        return sdate;
    }

    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.C_NO
     *
     * @return the value of custom.C_NO
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public Integer getcNo() {
        return cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.C_NO
     *
     * @param cNo the value for custom.C_NO
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setcNo(Integer cNo) {
        this.cNo = cNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.C_NAME
     *
     * @return the value of custom.C_NAME
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.C_NAME
     *
     * @param cName the value for custom.C_NAME
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.ID_CARD
     *
     * @return the value of custom.ID_CARD
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.ID_CARD
     *
     * @param idCard the value for custom.ID_CARD
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.SEX
     *
     * @return the value of custom.SEX
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.SEX
     *
     * @param sex the value for custom.SEX
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.PHONE
     *
     * @return the value of custom.PHONE
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.PHONE
     *
     * @param phone the value for custom.PHONE
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.ADDRESS
     *
     * @return the value of custom.ADDRESS
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.ADDRESS
     *
     * @param address the value for custom.ADDRESS
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.EMAIL
     *
     * @return the value of custom.EMAIL
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.EMAIL
     *
     * @param email the value for custom.EMAIL
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.HOBBY
     *
     * @return the value of custom.HOBBY
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.HOBBY
     *
     * @param hobby the value for custom.HOBBY
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column custom.CREATED_DATE
     *
     * @return the value of custom.CREATED_DATE
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column custom.CREATED_DATE
     *
     * @param createdDate the value for custom.CREATED_DATE
     *
     * @mbggenerated Sun Apr 15 12:00:30 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}