package com.chatRobot.model;

public class fundaccount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundaccount.ID
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundaccount.C_ID
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundaccount.ac_num
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    private Integer acNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundaccount.F_NO
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    private String fNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundaccount.price
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fundaccount.count
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    private Float count;


    private String sdate;

    public String getSdate() {
        return sdate;
    }

    public void setSdate(String sdate) {
        this.sdate = sdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundaccount.ID
     *
     * @return the value of fundaccount.ID
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundaccount.ID
     *
     * @param id the value for fundaccount.ID
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundaccount.C_ID
     *
     * @return the value of fundaccount.C_ID
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundaccount.C_ID
     *
     * @param cId the value for fundaccount.C_ID
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundaccount.ac_num
     *
     * @return the value of fundaccount.ac_num
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public Integer getAcNum() {
        return acNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundaccount.ac_num
     *
     * @param acNum the value for fundaccount.ac_num
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public void setAcNum(Integer acNum) {
        this.acNum = acNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundaccount.F_NO
     *
     * @return the value of fundaccount.F_NO
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public String getfNo() {
        return fNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundaccount.F_NO
     *
     * @param fNo the value for fundaccount.F_NO
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public void setfNo(String fNo) {
        this.fNo = fNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundaccount.price
     *
     * @return the value of fundaccount.price
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundaccount.price
     *
     * @param price the value for fundaccount.price
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fundaccount.count
     *
     * @return the value of fundaccount.count
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public Float getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fundaccount.count
     *
     * @param count the value for fundaccount.count
     *
     * @mbggenerated Wed Apr 18 17:56:19 CST 2018
     */
    public void setCount(Float count) {
        this.count = count;
    }
}