package com.chatRobot.model;

import java.util.Date;

public class Sales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.S_ID
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private Integer sId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.USSERNAME
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private String ussername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.PASSWORD
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.REALNAME
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.SEX
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.PHONE_NO
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.CREATED_DATA
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private Date createdData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.PERMISSION
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private Integer permission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales.POSITION
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    private String position;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.S_ID
     *
     * @return the value of sales.S_ID
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.S_ID
     *
     * @param sId the value for sales.S_ID
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.USSERNAME
     *
     * @return the value of sales.USSERNAME
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public String getUssername() {
        return ussername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.USSERNAME
     *
     * @param ussername the value for sales.USSERNAME
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setUssername(String ussername) {
        this.ussername = ussername == null ? null : ussername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.PASSWORD
     *
     * @return the value of sales.PASSWORD
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.PASSWORD
     *
     * @param password the value for sales.PASSWORD
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.REALNAME
     *
     * @return the value of sales.REALNAME
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.REALNAME
     *
     * @param realname the value for sales.REALNAME
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.SEX
     *
     * @return the value of sales.SEX
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.SEX
     *
     * @param sex the value for sales.SEX
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.PHONE_NO
     *
     * @return the value of sales.PHONE_NO
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.PHONE_NO
     *
     * @param phoneNo the value for sales.PHONE_NO
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.CREATED_DATA
     *
     * @return the value of sales.CREATED_DATA
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public Date getCreatedData() {
        return createdData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.CREATED_DATA
     *
     * @param createdData the value for sales.CREATED_DATA
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setCreatedData(Date createdData) {
        this.createdData = createdData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.PERMISSION
     *
     * @return the value of sales.PERMISSION
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.PERMISSION
     *
     * @param permission the value for sales.PERMISSION
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales.POSITION
     *
     * @return the value of sales.POSITION
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales.POSITION
     *
     * @param position the value for sales.POSITION
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }
}