package com.chatRobot.model;

public class User_p {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_p.id
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_p.name
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_p.password
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_p.id
     *
     * @return the value of user_p.id
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_p.id
     *
     * @param id the value for user_p.id
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_p.name
     *
     * @return the value of user_p.name
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_p.name
     *
     * @param name the value for user_p.name
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_p.password
     *
     * @return the value of user_p.password
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_p.password
     *
     * @param password the value for user_p.password
     *
     * @mbggenerated Thu Jan 04 15:28:26 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}