package com.chatRobot.dao;

import com.chatRobot.model.account;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface accountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Apr 16 18:14:42 CST 2018
     */
    int deleteByPrimaryKey(Integer acNum);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Apr 16 18:14:42 CST 2018
     */
    int insert(account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Apr 16 18:14:42 CST 2018
     */
    int insertSelective(account record);


    long getCount();
    List<account> getAll(@Param("startPos")int startPos, @Param("pageSize")int pageSize);

    long getaccountCount(int acNum);
    List<account> selectByPage(@Param("acNum")int acNum, @Param("startPos")int startPos, @Param("pageSize")int pageSize);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Apr 16 18:14:42 CST 2018
     */
    account selectByPrimaryKey(Integer acNum);

    List<account> selectBycNo(Integer cNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Apr 16 18:14:42 CST 2018
     */
    int updateByPrimaryKeySelective(account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account
     *
     * @mbggenerated Mon Apr 16 18:14:42 CST 2018
     */
    int updateByPrimaryKey(account record);
}