package com.chatRobot.dao;

import com.chatRobot.model.fundaccount;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface fundaccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundaccount
     *
     * @mbggenerated Wed Apr 18 14:54:11 CST 2018
     */
    int deleteByPrimaryKey(Integer id);


    List <fundaccount> findByIdsMap(List<String> ids);


    int updateByfNo(@Param("price")float price,@Param("fNo")String fNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundaccount
     *
     * @mbggenerated Wed Apr 18 14:54:11 CST 2018
     */
    int insert(fundaccount record);


    long getCount(int acNum);
    List<fundaccount> selectByPage(@Param("acNum")int acNum,@Param("startPos")int startPos, @Param("pageSize")int pageSize);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundaccount
     *
     * @mbggenerated Wed Apr 18 14:54:11 CST 2018
     */
    int insertSelective(fundaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundaccount
     *
     * @mbggenerated Wed Apr 18 14:54:11 CST 2018
     */
    fundaccount selectByPrimaryKey(Integer id);


    List<fundaccount> selectBycIdAndfNo(@Param("cId") int cId,@Param("fNo") String fNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundaccount
     *
     * @mbggenerated Wed Apr 18 14:54:11 CST 2018
     */
    int updateByPrimaryKeySelective(fundaccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fundaccount
     *
     * @mbggenerated Wed Apr 18 14:54:11 CST 2018
     */
    int updateByPrimaryKey(fundaccount record);
}