package com.chatRobot.dao;

import com.chatRobot.model.Sales;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int insertSelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    Sales selectByPrimaryKey(Integer sId);
//    @Select("select * from sales where S_ID =#{sId} and PASSWORD=#{password}")
//    @Select("select * from sales where S_ID =#{sId} and PASSWORD=#{password}") limit 0,#{size}
    Sales selectByPrimaryKeyandPassword(@Param("sId") Integer sId, @Param("password") String password);
    long getSalesCount(String param);
    List<Sales> selectByPage(@Param("param")String param, @Param("startPos")int startPos,@Param("pageSize")int pageSize);
//    @Select("select * from sales limit 0,#{size}")
    List<Sales> selectAll(int size);

    @Select("select * from sales where PHONE_NO =#{phone}")
    Sales selectByPhone(String phone);

//    @Select("select * from sales REALNAME=#{relname}")
    List<Sales> selectByRealname(String realname);

    List<Sales> selectByUsername(String Username);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int updateByPrimaryKeySelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int updateByPrimaryKey(Sales record);
}