package com.chatRobot.dao;

import com.chatRobot.model.Sales;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface SalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int insert(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int insertSelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    Sales selectByPrimaryKey(Integer sId);
    @Select("select count(*) from sales where S_ID =#{sId} and PASSWORD=#{password}")
//    @Select("select count(*) from sales where S_ID =#{sId} and PASSWORD=#{password}")
    int selectByPrimaryKeyandPassword(@Param("sId") Integer sId, @Param("password") String password);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int updateByPrimaryKeySelective(Sales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sales
     *
     * @mbggenerated Fri Jan 12 13:56:43 CST 2018
     */
    int updateByPrimaryKey(Sales record);
}